{{- if .Values.sidecar.podDisruptionBudget.enabled }}
---
apiVersion: {{ include "sentineltranslate.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentineltranslate.sidecar.fullname" . }}
  labels:
    {{- include "sentineltranslate.labels" . | nindent 4 }}
    app.kubernetes.io/component: sidecar
spec:
  {{- if .Values.sidecar.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.sidecar.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.sidecar.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.sidecar.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sentineltranslate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sidecar
{{- end }}
---
{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: {{ include "sentineltranslate.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentineltranslate.api.fullname" . }}
  labels:
    {{- include "sentineltranslate.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if .Values.api.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.api.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sentineltranslate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
---
{{- if .Values.worker.podDisruptionBudget.enabled }}
apiVersion: {{ include "sentineltranslate.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentineltranslate.worker.fullname" . }}
  labels:
    {{- include "sentineltranslate.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if .Values.worker.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.worker.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.worker.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sentineltranslate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
