{{- if .Values.triton.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentineltranslate.triton.serviceAccountName" . }}
  labels:
    {{- include "sentineltranslate.labels" . | nindent 4 }}
    app.kubernetes.io/component: triton
{{- end }}
---
{{- if .Values.sidecar.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentineltranslate.sidecar.serviceAccountName" . }}
  labels:
    {{- include "sentineltranslate.labels" . | nindent 4 }}
    app.kubernetes.io/component: sidecar
{{- end }}
---
{{- if and .Values.api.enabled .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentineltranslate.api.serviceAccountName" . }}
  labels:
    {{- include "sentineltranslate.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if and .Values.worker.enabled .Values.worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentineltranslate.worker.serviceAccountName" . }}
  labels:
    {{- include "sentineltranslate.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
