apiVersion: v1
kind: Service
metadata:
  name: lang-detect-service
  labels:
    app: lang-detect-service
    component: microservice
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lang-detect-service
